apiVersion: v1
kind: Service
metadata:
  name: service-ingestion
  labels:
    app: service-ingestion
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: service-ingestion
