apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-ingestion
  labels:
    app: service-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-ingestion
  template:
    metadata:
      labels:
        app: service-ingestion
    spec:
      containers:
      - name: service-ingestion
        image: log-analyzer/service-ingestion:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
