apiVersion: v1
kind: Service
metadata:
  name: service-analytics
  labels:
    app: service-analytics
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
  selector:
    app: service-analytics
