apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-analytics
  labels:
    app: service-analytics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-analytics
  template:
    metadata:
      labels:
        app: service-analytics
    spec:
      containers:
      - name: service-analytics
        image: log-analyzer/service-analytics:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3002
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3002"
        - name: GROQ_API_KEY
          value: "your-groq-api-key-here"
